# Assignment Operators in Python
# Simple Assignment (=)
x = 10
print("Simple Assignment (x = 10):", x)  # Output: 10
# Addition Assignment (+=)
y = 5
y += 3
print("Addition Assignment (y += 3):", y)  # Output: 8
# Subtraction Assignment (-=)
z = 15
z -= 5
print("Subtraction Assignment (z -= 5):", z)  # Output: 10
# Multiplication Assignment (*=)
a = 4
a *= 2
print("Multiplication Assignment (a *= 2):", a)  # Output: 8
# Division Assignment (/=)
b = 20
b /= 4
print("Division Assignment (b /= 4):", b)   # Output: 5.0
# Modulus Assignment (%=)
c = 10
c %= 3
print("Modulus Assignment (c %= 3):", c)  # Output: 1
# Exponentiation Assignment (**=)
d = 2
d **= 3
print("Exponentiation Assignment (d **= 3):", d)  # Output: 8
